### ISSUE TITLE
No module named 'cairo' when running notebooks/Modulation.ipynb

### ISSUE THREAD

**Issue by dwsl** [drexelwireless/dragonradio#3]
1) Fresh install of the newest dragonradio master
2) sourced the environment (source env/bin/activate)
3) jypiter notebook -> load -> notebooks/Modulation.ipynb
4) Running the script leads to: No module named 'cairo' and No module named "cairocffi'

**Comment by mainland** [comment]
OK, how about you have a go at fixing this. Can you provide a commit hash, since "newest dragonradio master" changes over time and is ambiguous in any case. The hash is in the image name!

**Comment by wnoc-drexel** [comment]
I was a bit vague in the original comment. We have a couple of STAR students that have setup Ubuntu 16 VMs. Alex and Marko have instructed them to install dragonradio on those VMs and run jyputer notebooks to test some code. They mentioned that for the time being we don't need to connect DR to any X310/N210. 

Newest dragonradio master is referring to 8d58fab35bb521f459abfd5685c3169a75dde338. It seems that this repo is not being updated with your latest changes in dwslgrid2. Are you using mainland/dragonradio?

Going back to the issue at hand, I'm pretty much sure that installing DR (at least this version) on a fresh ubuntu image and getting all the dependencies right might just be a trial and error process. When was the last time you tried installing DR on a fresh Ubuntu image? In any case, we can close this ticket and I'll try to get jyputer sorted out this week if possible and keep notes as to what I did.

Vasil

**Comment by mainland** [comment]
Every time an image is built, it's built on a fresh Ubuntu install.

If you want to use the tools, you need to run the `install.sh` in the tools directory, which will create a virtualenv environment named `env` in the tools directory. Use that to run the tools. Is that what you tried?

**Comment by wnoc-drexel** [comment]
Started everything from scratch.
1) Fresh ubuntu 16 image on VirtualBox - no issues
2) Cloned dragonradio 8d58fab35bb521f459abfd5685c3169a75dde338 - no issues
3) Installed dragonradio with build.sh (needed to install curl separately so build.sh needs to be updated with curl)
4) Ran install.sh under dragonradion/tools - no issues
5) Ran source dragonradio/tools/env/bin/activate - no issues
6) Ran jupyter notebook then loaded Modulation.ipynb - no issues
7) Ran code with Run button got the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-4f67a6d11c74> in <module>
     14 import drgui
     15 
---> 16 from dragonsignal import *

~/dragonradio/tools/dragonsignal.py in <module>
     14 import drgui
     15 
---> 16 HEADER_MCS = dragonradio.liquid.MCS('crc32', 'secded7264', 'h84', 'bpsk')
     17 """MCS used for packet headers"""
     18 

AttributeError: module 'dragonradio' has no attribute 'liquid'
```

I can work on a fix but any pointers are welcomed.

**Comment by mainland** [comment]
I'm afraid I don't have time to go back and get things working on an old version of Ubuntu. The tools have been rewritten and I'm trying to get a new release out that supports Ubuntu 20.04 and UHD 3.15.

A recurring problem is that even older versions of pip wheels have been updated to use shared libraries that are newer than the ones present on Ubuntu 16.04, so locking versions in `requirements.txt` doesn't help. The tools certainly work on the images we used for ECET 480/680, so if you have to use the tools, use those. At some point I'll have a version updated for Ubuntu 20.04, but given how slammed I am this term, that won't happen for some time.

**Comment by wnoc-drexel** [comment]
Completely understood. No problem at all. Let me know when I can test the new 20.04 release on a VM!
